
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.NumberFormat;


 
/**
 *
 * @author yamdangar
 */
public class CashReg extends javax.swing.JFrame {
 
    /**
     * Creates new form CNR_GUI
     */
    double totalsale;
    double[] price = new double[6];
    
    double itotal;
    int iquantity;
    double ipaid;
    double change;
    int stotal = 0;
    String[] receipt = new String[4]; //Arrray for receipt
    double totalCost = 0;

    NumberFormat formatter = NumberFormat.getCurrencyInstance();
    int[][] notes = new int[5][2]; //Array for notes

    int[][] coins = new int[6][2];
    
    
    
    
    public CashReg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Total = new javax.swing.JTextPane();
        jLabelSalePrice = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        radSchnitzelRoll = new javax.swing.JRadioButton();
        radFishRoll = new javax.swing.JRadioButton();
        radLambRoll = new javax.swing.JRadioButton();
        radIceCreamRoll = new javax.swing.JRadioButton();
        radCoffeeLatte = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textChangeCurrency = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnDone = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        textQuantity = new javax.swing.JTextField();
        textPaid = new javax.swing.JTextField();
        textChange = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textDailySummary = new javax.swing.JTextPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 3, 16)); // NOI18N
        jLabel1.setText("Coffe N Roll Cash Register");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        Total.setForeground(new java.awt.Color(255, 0, 0));
        jScrollPane5.setViewportView(Total);

        jLabelSalePrice.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelSalePrice.setForeground(new java.awt.Color(255, 0, 0));
        jLabelSalePrice.setText("Sale price");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabelSalePrice)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSalePrice)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Coffe N Roll Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N
        jPanel3.setToolTipText("");
        jPanel3.setPreferredSize(new java.awt.Dimension(276, 162));
        jPanel3.setSize(new java.awt.Dimension(100, 100));

        radSchnitzelRoll.setText(" 1. Schnitzel Roll                    $18.80");
        radSchnitzelRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radSchnitzelRollActionPerformed(evt);
            }
        });

        radFishRoll.setText("2. Fish Roll                            $17.25");
        radFishRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radFishRollActionPerformed(evt);
            }
        });

        radLambRoll.setText("3. Lamb Roll                          $14.60");
        radLambRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radLambRollActionPerformed(evt);
            }
        });

        radIceCreamRoll.setText("4. Ice Cream Roll                   $6.75");
        radIceCreamRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radIceCreamRollActionPerformed(evt);
            }
        });

        radCoffeeLatte.setText("5. Coffee Latte                      $3.40");
        radCoffeeLatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCoffeeLatteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radSchnitzelRoll)
                    .addComponent(radFishRoll)
                    .addComponent(radLambRoll)
                    .addComponent(radIceCreamRoll)
                    .addComponent(radCoffeeLatte))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(radSchnitzelRoll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radFishRoll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radLambRoll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radIceCreamRoll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radCoffeeLatte))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Change currency denominations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N
        jPanel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(276, 162));

        jScrollPane1.setViewportView(textChangeCurrency);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setPreferredSize(new java.awt.Dimension(276, 162));

        jLabel2.setText("Quantity");
        jLabel2.setMinimumSize(new java.awt.Dimension(54, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(54, 14));
        jLabel2.setSize(new java.awt.Dimension(45, 14));

        jLabel3.setText("Paid (cents)");
        jLabel3.setMaximumSize(new java.awt.Dimension(72, 14));
        jLabel3.setMinimumSize(new java.awt.Dimension(72, 14));
        jLabel3.setPreferredSize(new java.awt.Dimension(72, 14));
        jLabel3.setSize(new java.awt.Dimension(45, 14));

        jLabel4.setText("Change");

        btnReset.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnDone.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnDone.setText("Done");
        btnDone.setMinimumSize(new java.awt.Dimension(79, 20));
        btnDone.setPreferredSize(new java.awt.Dimension(79, 20));
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 102, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        textQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textQuantityActionPerformed(evt);
            }
        });

        textPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPaidActionPerformed(evt);
            }
        });
        textPaid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPaidKeyTyped(evt);
            }
        });

        textChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textChangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(textPaid)
                            .addComponent(textChange)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Daily trading summary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(276, 162));

        jScrollPane3.setViewportView(textDailySummary);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setPreferredSize(new java.awt.Dimension(276, 162));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CashReg1.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radCoffeeLatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCoffeeLatteActionPerformed
        // This option selects Coffe Latte option
         if  (radCoffeeLatte.isSelected()) {
            textQuantity.setEnabled(true);//This enables the quantity text area
            radSchnitzelRoll.setSelected(false);
            radIceCreamRoll.setSelected(false);
            radFishRoll.setSelected(false);
            radLambRoll.setSelected(false);
        } else {
            textQuantity.setEnabled(false); // This disables the quantity text area
        }
    }//GEN-LAST:event_radCoffeeLatteActionPerformed

    private void radFishRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radFishRollActionPerformed
        // This option selects Fish Roll
        if  (radFishRoll.isSelected()) {
            textQuantity.setEnabled(true);//This enables the quantity text area
            radSchnitzelRoll.setSelected(false);
            radIceCreamRoll.setSelected(false);
            radCoffeeLatte.setSelected(false);
            radLambRoll.setSelected(false);
        } else {
            textQuantity.setEnabled(false); // This disables the quantity text area
        }
    }//GEN-LAST:event_radFishRollActionPerformed

    private void radLambRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radLambRollActionPerformed
        // This option selects Lamb Roll
        if  (radLambRoll.isSelected()) {
            textQuantity.setEnabled(true);//This enables the quantity text area
            radSchnitzelRoll.setSelected(false);
            radIceCreamRoll.setSelected(false);
            radFishRoll.setSelected(false);
            radCoffeeLatte.setSelected(false);
        } else {
            textQuantity.setEnabled(false); // This disables the quantity text area
        }
    }//GEN-LAST:event_radLambRollActionPerformed

    private void radIceCreamRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radIceCreamRollActionPerformed
        // This option selects Ice Cream roll
         if  (radIceCreamRoll.isSelected()) {
            textQuantity.setEnabled(true);//This enables the quantity text area
            radSchnitzelRoll.setSelected(false);
            radFishRoll.setSelected(false);
            radCoffeeLatte.setSelected(false);
            radLambRoll.setSelected(false);
        } else {
            textQuantity.setEnabled(false); // This disables the quantity text area
        }
    }//GEN-LAST:event_radIceCreamRollActionPerformed

    private void radSchnitzelRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSchnitzelRollActionPerformed
       // this option selects Schnitzel Roll
        if  (radSchnitzelRoll.isSelected()) {
            textQuantity.setEnabled(true);//This enables the quantity text area
            radCoffeeLatte.setSelected(false);
            radIceCreamRoll.setSelected(false);
            radFishRoll.setSelected(false);
            radLambRoll.setSelected(false);
        } else {
            textQuantity.setEnabled(false); // This disables the quantity text area
        }
    }//GEN-LAST:event_radSchnitzelRollActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // This button will reset all order
        
        textChange.setText(null);
        textChangeCurrency.setText(null);
        textDailySummary.setText(null);
        textPaid.setText(null);
        textQuantity.setText(null);
        Total.setText(null);
        radSchnitzelRoll.setSelected(false);
        radFishRoll.setSelected(false);
        radLambRoll.setSelected(false);
        radIceCreamRoll.setSelected(false);
        radCoffeeLatte.setSelected(false);  
       
    
    }//GEN-LAST:event_btnResetActionPerformed
//@Override
    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
     
        
    }//GEN-LAST:event_btnDoneActionPerformed

    private void textQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textQuantityActionPerformed
        // TODO add your handling code here:
                if (textQuantity.isEnabled()) {
            textPaid.setEnabled(true);
        } else {
            textPaid.setEnabled(false);
        }
        iquantity = (int) Double.parseDouble(textQuantity.getText());
        if (radSchnitzelRoll.isSelected()) {
            price[1] = 18.80;
            totalCost = iquantity * price[1];

        }

        if (radFishRoll.isSelected()) {
            price[2] = 17.25;
            totalCost = iquantity * price[2];
            

        }
        if (radLambRoll.isSelected()) {
            price[3] = 14.60;
            totalCost = iquantity * price[3];

        }
        if (radIceCreamRoll.isSelected()) {
            price[4] = 6.75;
            totalCost = iquantity * price[4];

        }
        if (radCoffeeLatte.isSelected()) {
            price[5] = 3.40;
            totalCost = iquantity * price[5];

        }

        String iAmount = String.format("$%.2f", totalCost);
        Total.setText(iAmount);

    }//GEN-LAST:event_textQuantityActionPerformed

    private void textChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textChangeActionPerformed
           // This button will gives change
           
    }//GEN-LAST:event_textChangeActionPerformed

    @SuppressWarnings("empty-statement")
    private void textPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPaidActionPerformed
        
         ipaid = Double.parseDouble(textPaid.getText());
        double totalAmount = totalCost;
        
       

         while (ipaid % 5 != 0 || ipaid < totalCost);
        change = ((ipaid / 100) - totalAmount);

        String ichange = String.format("$%.2f", change);
        if (change > 0) {
            textChange.setText(ichange);
        } else {
            textChange.setText("0.00");
        }
        
        
        ///start
        double payToCust = change;
        StringBuffer buff = new StringBuffer();
            int count = 0;
          
           //Login to calculate coins type
            while(payToCust >= 0.0) {
              
                while(payToCust >= 20.0) {
                    count++;
                    payToCust = payToCust - 20.0;
                }
              
                if(count > 0) {
                     buff.append("|Number of 20 dollar notes: ").append(count).append(" |").append("\n");
                     count = 0;
                }
                System.out.println(buff.toString());
              
                while(payToCust >= 2.0) {
                    count++;
                    payToCust = payToCust - 2.0;
                }
              
                if(count > 0) {
                     buff.append("|Number of 2 dollar coins: ").append(count).append(" |").append("\n");
                     count = 0;
                }
                System.out.println(buff.toString());
              
                while(payToCust >= 1.0) {
                    count++;
                    payToCust = payToCust - 1.0;
                }
              
                if(count > 0) {
                     buff.append("|Number of 1 dollar coins: ").append(count).append(" |").append("\n");
                     count = 0;
                }
                System.out.println(buff.toString());
              
                while(payToCust >= 0.50) {
                    count++;
                    payToCust = payToCust - 0.50;
                }
              
                if(count > 0) {
                     buff.append("|Number of 50 cents coins: ").append(count).append(" |").append("\n");
                     count = 0;
                }
                System.out.println(buff.toString());
              
                while(payToCust >= 0.20) {
                    count++;
                    payToCust = payToCust - 0.20;
                }
              
                if(count > 0) {
                     buff.append("|Number of 20 cents coins: ").append(count).append(" |").append("\n");
                     count = 0;
                }
                System.out.println(buff.toString());
              
                if(payToCust > 0 && payToCust < .50)
                    payToCust = payToCust + .05;
              
                while(payToCust >= 0.05) {
                    count++;
                    payToCust = payToCust - 0.05;
                }
              
                if(count > 0) {
                     buff.append("|Number of 5 cents coins: ").append(count).append(" |").append("\n");
                     count = 0;
                }
              
               //setting refund coins value on GUI
               payToCust = -1;
                textChangeCurrency.setText(buff.toString());
              
              
               //Setting up Daily Sales
               StringBuffer buf = new StringBuffer();
               buf.append("Total \n").append("Daily Sales: \n").append("$").append(String.format("%.2f",totalCost));
               textDailySummary.setText(buf.toString());
            }
       
    }//GEN-LAST:event_textPaidActionPerformed

    private void textPaidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPaidKeyTyped
        // TODO add your handling code here:
        char iNum = evt.getKeyChar();
        if (!(Character.isDigit(iNum))
                || (iNum == KeyEvent.VK_BACK_SPACE)
                || (iNum == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_textPaidKeyTyped

    
    
     
     
               
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CashReg().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane Total;
    private javax.swing.JButton btnDone;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelSalePrice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JRadioButton radCoffeeLatte;
    private javax.swing.JRadioButton radFishRoll;
    private javax.swing.JRadioButton radIceCreamRoll;
    private javax.swing.JRadioButton radLambRoll;
    private javax.swing.JRadioButton radSchnitzelRoll;
    private javax.swing.JTextField textChange;
    private javax.swing.JTextPane textChangeCurrency;
    private javax.swing.JTextPane textDailySummary;
    private javax.swing.JTextField textPaid;
    private javax.swing.JTextField textQuantity;
    // End of variables declaration//GEN-END:variables

    private Object btnDonegetActionCommand() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static class e {

        private static Object getActionCommand() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public e() {
        }
    }
}
